name: Museion Ukraine
favicon: null
layout_spectrum: 0.43238340714015067
typography_spectrum: 0.7928833840414882
title: Museion Ukraine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b97d8'
    - '#8db9e8'
    - '#a68751'
    - '#d5b07b'
    - '#674d1a'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
