name: Museion Ukraine
favicon: null
layout_spectrum: 0.70027
typography_spectrum: 0.89993
title: Museion Ukraine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120d0a'
    - '#cc9f38'
    - '#7a9ed2'
    - '#547eae'
    - '#94c7fb'
  brandStrength: 0.125
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
